
CMAKE_POLICY(SET CMP0011 NEW)

IF (KOKKOS_ENABLE_EMU)
   FIND_PACKAGE(Emu REQUIRED)

   KOKKOS_TPL_OPTION(EMU On)

   KOKKOS_LINK_TPL(kokkoscore PUBLIC IMPORTED_NAME Emu::emu EMU)
ELSE()

  TARGET_COMPILE_OPTIONS(
      kokkoscore
      PUBLIC $<$<COMPILE_LANGUAGE:CXX>:-fcilkplus>
  )
  GLOBAL_APPEND(KOKKOS_LINK_OPTIONS ${COMPILER_SPECIFIC_FLAGS_TMP})
ENDIF()
