CMAKE_POLICY(SET CMP0011 NEW)

list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/Modules")

IF (KOKKOS_ENABLE_EMU)
   IF (KOKKOS_EMU_X86)
      TARGET_COMPILE_OPTIONS(
         kokkoscore
         PUBLIC $<$<COMPILE_LANGUAGE:CXX>:-fcilkplus>
      )
      GLOBAL_APPEND(KOKKOS_LINK_OPTIONS -fcilkplus)
   ELSE()
      FIND_PACKAGE(EMU REQUIRED)

      KOKKOS_TPL_OPTION(EMU On)

      KOKKOS_LINK_TPL(kokkoscore PUBLIC IMPORTED_NAME EMU::emu EMU)
   ENDIF()
ELSE()

  TARGET_COMPILE_OPTIONS(
      kokkoscore
      PUBLIC $<$<COMPILE_LANGUAGE:CXX>:-fcilkplus>
  )
  GLOBAL_APPEND(KOKKOS_LINK_OPTIONS -fcilkplus)
ENDIF()
